name: Android CI

on:
  pull_request:
    branches:
      - developer
  push:
    branches:
      - developer
      - main

jobs:
  check-kotlin-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install ktlint
        run: ./gradlew ktlintCheck

  run-unit-tests:
    runs-on: ubuntu-latest
    needs: check-kotlin-format
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run unit tests
        run: ./gradlew test

  build-apks:
    runs-on: ubuntu-latest
    needs: run-unit-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build APKs
        run: |
          ./gradlew assembleDebug
          ./gradlew assembleRelease

      - name: Rename APKs
        run: ./gradlew renameApks
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

  create-tag:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create a new tag
        run: |
          TAG_NAME="release-$(date +'%Y-%m-%d')"
          git tag $TAG_NAME
          git push origin $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
